name: Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Check PHP syntax errors
      uses: overtrue/phplint@9.1.2
      
  code-quality-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: PHP Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          php_version: 8.2
          path: www/
          report: csv
          report_file: code_quality.csv

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: quality_report
          path: code_quality.csv
          retention-days: 5
